steps:
  # Paso 1: Instalar dependencias y ejecutar el script de generación del modelo en el mismo contenedor
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r Generacion_Modelo/requirements.txt &&
        python3 Generacion_Modelo/generar_modelo.py  # Ejecutar el script sin mover el archivo

  # Paso 2: Construir la imagen Docker, incluyendo el modelo generado
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/caso_estudio_2:v1', '-f', 'contenedor/Dockerfile', '.']

  # Paso 3: Publicar la imagen en Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/caso_estudio_2:v1']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
